#### Basics of Numpy

In [ ]:
import numpy as np

In [2]:
list = [1,2,3]
npArray = np.array(list)
npArray

array([1, 2, 3])

In [3]:
print(type(list))
print(type(npArray))

<class 'list'>
<class 'numpy.ndarray'>


In [4]:
npArray.shape

(3,)

In [42]:
list2 = [[1,2,3], [4,5,6]]
a = np.array(list2)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.shape

(2, 3)

In [17]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
a.reshape((6,))

array([1, 2, 3, 4, 5, 6])

##### Constructing an array

In [22]:
np.zeros((3,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [21]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [24]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
np.linspace(1,10,num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

##### Indexing

In [33]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
print(a[0])
print()
print(a[:])
print()
print(a[1][1])
print()

[1 2 3]

[[1 2 3]
 [4 5 6]]

5



##### Operations

In [41]:
a*2

# Without Numpy

# for i in range(2):
#     for j in range(3):
#         a[i,j] *= 2
# a

array([[ 8, 16, 24],
       [32, 40, 48]])

In [46]:
a > 4

array([[False, False, False],
       [False,  True,  True]])

In [47]:
a[a>4]

array([5, 6])

In [51]:
np.mean(a,axis=0)

# axis=0 : for Columns
# axis=1 : for Rows

array([2.5, 3.5, 4.5])

In [53]:
np.std(a,axis=1)

array([0.81649658, 0.81649658])

In [54]:
np.concatenate([a,a*2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 2,  4,  6],
       [ 8, 10, 12]])

#### Applications


In [1]:
from keras.datasets import mnist

In [2]:
(X_train,Y_train),(X_test,Y_train) = mnist.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [5]:
#Image Dataset

X_train.shape

(60000, 28, 28)

In [6]:
import pandas as pd

In [8]:
df = pd.read_csv('../DATA/Iris.csv')
df

Id  SepalLengthCm  ...  PetalWidthCm         Species
0      1            5.1  ...           0.2     Iris-setosa
1      2            4.9  ...           0.2     Iris-setosa
2      3            4.7  ...           0.2     Iris-setosa
3      4            4.6  ...           0.2     Iris-setosa
4      5            5.0  ...           0.2     Iris-setosa
..   ...            ...  ...           ...             ...
145  146            6.7  ...           2.3  Iris-virginica
146  147            6.3  ...           1.9  Iris-virginica
147  148            6.5  ...           2.0  Iris-virginica
148  149            6.2  ...           2.3  Iris-virginica
149  150            5.9  ...           1.8  Iris-virginica

[150 rows x 6 columns]

In [9]:
df.to_numpy().shape

(150, 6)